### ISSUE TITLE
\usepackage{XXX}

### ISSUE THREAD

**Issue by lixiang007666** [sylvainhalle/PaperShell#17]
Because the preamble.inc.tex file will be overwritten after `make`.

If I want to introduce my own additional `packages` before `make`, what changes need to be made?

EX:
```latex
\usepackage{booktabs}
\usepackage{adjustbox}
\usepackage{threeparttable}
```

**Comment by sylvainhalle** [comment]
You should use the file `includes.tex` to write these instructions. This file is left untouched when you run the scripts.

**Comment by lixiang007666** [comment]
thanks! @sylvainhalle
