### ISSUE TITLE
running php file

### ISSUE THREAD

**Issue by nicenice134** [sylvainhalle/PaperShell#19]
Hi there, 

really thankful for your work, but I have an Issue. 
I modified the authors.txt file but I cant seem to translate it into the then compiled pdf.
I downloaded and installed php. Folderstructure is:

Main
- PHP
- -php.exe
- PaperShell
- -source folder
- --paper.tex
- --etc.
- -set-style.php
- -authors.txt
- -etc.

It seems im not running the set-style file correctly, i tried for cmd: php set-style.php lncs
but it didnt work out yet. And ideas? Thanks in advance.

Best,
Binel

**Comment by sylvainhalle** [comment]
What do you mean by "didn't work out"? Please post the error message so that I can help you out.

**Comment by nicenice134** [comment]
thanks for the quick response
Was not able to open input file: set-style.php

**Comment by nicenice134** [comment]
I tried running it with xampp this time around, error: 

Warning: Undefined variable $argv in C:\xampp\htdocs\set-style.php on line 73

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in C:\xampp\htdocs\set-style.php:73 Stack trace: #0 {main} thrown in C:\xampp\htdocs\set-style.php on line 73

**Comment by sylvainhalle** [comment]
Looks like a problem with your PHP setup. I see that you are using Windows with Xampp. Here are a few things I suggest you check:

1. Make sure that the PHP executable is in your path --that is, you should be able to call `php` at the command line from any folder. Instructions here: https://www.youtube.com/watch?v=LHOmrCbP0g8
2. Make sure that the contents of the PaperShell repository is all copied in some local folder on your machine. Given the error message you gave me, it seems like it was copied in the htdocs folde, which I don't recommend. It is better to place the project somewhere under the "My Documents" folder (although PaperShell uses PHP, it has nothing to do with a web server).
3. Open a command prompt and use the `cd` command to go to the folder where your PaperShell root is. This is where `set-style.php` should be.
4. Don't forget that `set-style.php` needs an argument, which is the style you want to apply to your paper. Please refer to PaperShell's readme for instructions.

If you don't mind I'll close the issue, as it does not seem to be related to a PaperShell bug.

**Comment by nicenice134** [comment]
Thanks, I got it to work. The make file doesnt work though.

**Comment by sylvainhalle** [comment]
It is possible that the makefile does not work in Windows, I never tested. But I'm glad you got the thing to work. Thanks for your input.
