### ISSUE TITLE
Makefile does not work in Windows

### ISSUE THREAD

**Issue by MiguelAVC** [sylvainhalle/PaperShell#20]
Hi, stumbled across this template in Overleaf and wanted to give it a try. Sadly, I followed the instructions all the way to compiling it. I am on a Windows machine and the error was the following:

PS D:\Papers\PaperShell-2.6.1\PaperShell-2.6.1\Source> make

The system cannot find the path specified.
process_begin: CreateProcess(NULL, which echo, ...) failed.
Makefile:834: pipe: Bad file descriptor
The system cannot find the path specified.
process_begin: CreateProcess(NULL, which tput, ...) failed.
Makefile:1104: pipe: Bad file descriptor
"NOTE: You may ignore warnings about the" "following files:" ; echo ; echo '     paper.d' ; echo ""
'kpsewhich' is not recognized as an internal or external command,
operable program or batch file.
'kpsewhich' is not recognized as an internal or external command,
operable program or batch file.
"= paper.tex --> paper.d paper.pdf.1st.make (0-1) ="
The system cannot find the path specified.
'/'' is not recognized as an internal or external command,
operable program or batch file.
Makefile:2898: paper.d: No such file or directory
make: *** [Makefile:3340: paper.d] Error 255

As far as I could google about it, syntax on the directories might be the issue. So yes, would you be supporting Windows on this?

**Comment by sylvainhalle** [comment]
Unfortunately the Makefile is something I took from [another project](https://github.com/shiblon/latex-makefile) and I am not involved in its development. The best chance you have is to ask the original author, but on my side there is not much that I can do.

That said, you can still use PaperShell and compile manually with the usual `pdflatex paper`. The PHP scripts themselves do not contain anything that is specific to Linux.
